### ISSUE TITLE
2 out of tree test failed from CADL-master\session-3\libs\vae.py

### ISSUE THREAD

**Issue by ehfo0** [pkmital/CADL#80]
```
ERROR: Train an autoencoder on Celeb Net.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\IDM\CADL-master\session-3\libs\vae.py", line 499, in test_celeb
    ckpt_name='./celeb.ckpt')
  File "D:\IDM\CADL-master\session-3\libs\vae.py", line 303, in train_vae
    shape=input_shape)
  File "D:\IDM\CADL-master\session-3\libs\dataset_utils.py", line 49, in create_input_pipeline
    files, capacity=len(files))
TypeError: object of type 'NoneType' has no len()
-------------------- >> begin captured stdout << ---------------------
Could not find celeb dataset under ./img_align_celeba/.
Try downloading the dataset from the "Aligned and Cropped" link located here (imgs/img_align_celeba.zip [1.34 GB]): http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html

--------------------- >> end captured stdout << ----------------------
```

**Comment by pkmital** [comment]
You should download the celeb dataset first.

**Comment by ehfo0** [comment]
that link to download celeb the cropped is dead is there another place to download the data set?
